
const envWithValuesInBase64 = {"BASE_URL":`eEFwV2RSclg5OWtQclZnZ0UiLyIK`,"MODE":`eEFwV2RSclg5OWtQclZnZ0UicHJvZHVjdGlvbiIK`,"DEV":`eEFwV2RSclg5OWtQclZnZ0VmYWxzZQo=`,"PROD":`eEFwV2RSclg5OWtQclZnZ0V0cnVlCg==`,"APP_VERSION":``,"REQUIRES_HARD_REFRESH":`eEFwV2RSclg5OWtQclZnZ0V0cnVlCg==`,"SENTRY_RELEASE":``,"LOAD_EXTERNAL_PACKAGES":`dHJ1ZQo=`,"BASE_PATH":``,"BASE_HREF":``,"PH_CONNECT_APP_REQUIRES_HARD_REFRESH":``,"SENTRY_AUTH_TOKEN":``,"SENTRY_ORG":``,"SENTRY_PROJECT":``,"LOG_LEVEL":`ZGVidWcK`,"PH_CONNECT_WARN_OUTDATED_APP":``,"PH_CONNECT_STUDIO_MODE":`dHJ1ZQo=`,"PH_CONNECT_ROUTER_BASENAME":``,"PH_CONNECT_DEFAULT_DRIVES_URL":``,"PH_CONNECT_ENABLED_EDITORS":``,"PH_CONNECT_DISABLE_ADD_PUBLIC_DRIVES":``,"PH_CONNECT_SEARCH_BAR_ENABLED":``,"PH_CONNECT_DISABLE_ADD_CLOUD_DRIVES":``,"PH_CONNECT_DISABLE_ADD_LOCAL_DRIVES":``,"PH_CONNECT_DISABLE_DELETE_PUBLIC_DRIVES":``,"PH_CONNECT_DISABLE_DELETE_CLOUD_DRIVES":``,"PH_CONNECT_DISABLE_DELETE_LOCAL_DRIVES":``,"PH_CONNECT_PUBLIC_DRIVES_ENABLED":``,"PH_CONNECT_CLOUD_DRIVES_ENABLED":``,"PH_CONNECT_LOCAL_DRIVES_ENABLED":``,"PH_CONNECT_ARBITRUM_ALLOW_LIST":``,"PH_CONNECT_RWA_ALLOW_LIST":``,"PH_CONNECT_HIDE_DOCUMENT_MODEL_SELECTION_SETTINGS":``,"PH_CONNECT_RENOWN_URL":``,"PH_CONNECT_RENOWN_NETWORK_ID":``,"PH_CONNECT_RENOWN_CHAIN_ID":``,"PH_CONNECT_DISABLED_EDITORS":``,"PH_CONNECT_SENTRY_DSN":``,"PH_CONNECT_SENTRY_PROJECT":``,"PH_CONNECT_SENTRY_ENV":``,"PH_CONNECT_SENTRY_TRACING_ENABLED":``,"PH_CONNECT_GA_TRACKING_ID":``,"LOCAL_DOCUMENT_MODELS":`Li9kb2N1bWVudC1tb2RlbHMK`,"LOCAL_DOCUMENT_EDITORS":`Li9lZGl0b3JzCg==`,"FILE_UPLOAD_OPERATIONS_CHUNK_SIZE":``,"PH_CONNECT_VERSION_CHECK_INTERVAL":``,"PH_CONNECT_CLI_VERSION":`MC40MC43Cg==`};
const env = {};
Object.keys(envWithValuesInBase64).forEach(function (name) {
  const value = new TextDecoder().decode(
    Uint8Array.from(
      atob(envWithValuesInBase64[name]),
      c => c.charCodeAt(0))
  ).slice(0,-1);
  env[name] = value.startsWith("xApWdRrX99kPrVggE") ? JSON.parse(value.slice("xApWdRrX99kPrVggE".length)) : value;
});
self.__VITE_ENVS = env;

